### ISSUE TITLE
Current Dragons Broncos match not available

### ISSUE THREAD

**Issue by tomtomtom123123** [aussieaddons/plugin.video.nrl-live#659]
Using a free Telstra account. The match was showing as upcoming however once it started it disappeared from the live games list.

**Comment by glennguy** [comment]
Hi @tomtomtom123123 
I put out an update shortly after the game started, version 1.2.5 which is available from the repo now.
If the update isn't showing for you, try this:
(in estuary skin)
go to add-ons
click the open box icon at the top left
install from repository
right click/long press/ 'c' button on our repo and select 'Check For Updates'
should be there now.

Cheers

Glenn

**Comment by glennguy** [comment]
Broadcast is finished btw but the live game listing is still showing if you wanted to check.

**Comment by tomtomtom123123** [comment]
Awesome thats working, thanks for the work glennguy

**Comment by glennguy** [comment]
@tomtomtom123123 you're welcome, happy to help

**Comment by glennguy** [comment]
fyi v1.3.0 is out, should fix any issues that you would have likely had the last couple of days. Closing this issue now, let me know if you have any more problems
