### ISSUE TITLE
Match highlights from  Rd 1, Dragons v Brisbane are not available 

### ISSUE THREAD

**Issue by shavanni** [aussieaddons/plugin.video.nrl-live#661]
Under match Highlights, only first nation highlights are displayed.

Rd 1 Dragons v broncos is not available

I'm on version 1.2.5

**Comment by shavanni** [comment]
This issue is still occuring. No recent match highlights are available

**Comment by glennguy** [comment]
I'll redo the main menu somewhat, watch this space. You can get the highlights from the videos menu for now.

**Comment by glennguy** [comment]
@shavanni 

I've made the changes, the addon now shows all the content the mobile app does.

You can try it out in version 1.3.0-1-ge836f8e from the [development repo](http://aussieaddons.com/development/)

**Comment by shavanni** [comment]
Brilliant work

Thanks so much

**Comment by glennguy** [comment]
Cheers, happy to help
