### ISSUE TITLE
Error when trying to play live stream

### ISSUE THREAD

**Issue by shavanni** [aussieaddons/plugin.video.nrl-live#662]
On v1.2.6, when trying to play the live stream, the following error is encountered. 
NRL Live v1.2.6 ERROR
Play.py (29) - UnboundLocalError: local cariable 'token' referenced before assignment

**Comment by ceptic** [comment]
Same here, was able to watch Rooster vs Tigers but now I am getting this message plus telling me v1.2.6 is outdated. Please upgrade to the latest version V1.2.7.... I cannot find v1.2.7 though

**Comment by shavanni** [comment]
Update to 1.2.7 fixed issue. Thanks so much

**Comment by glennguy** [comment]
@shavanni  @ceptic  v1.3.0 is now out, please update and let me know if you have any further issues
