### ISSUE TITLE
Error after upgrade to V1.2.7

### ISSUE THREAD

**Issue by ceptic** [aussieaddons/plugin.video.nrl-live#664]
After v1.2.6 started with errors I upgraded to v1.2.7 and now get the following error;
play.py (32) - Http error:401 Client Error: Unauthorised for url: https://API.telstra.com/v1/media-entitlements/entitlements?IDP=T[ 

Apparently v1.2.7 works for others?

**Comment by Gumster5** [comment]
No luck here either, stuck watching on the tiny phone screen...

**Comment by glennguy** [comment]
Hey guys,

If you're not seeing the latest version in the repo:
(in estuary skin)
go to add-ons
click the open box icon at the top left
install from repository
right click/long press/ 'c' button on our repo and select 'Check For Updates'
should be there now.

As of this minute, free live pass isn't working properly but will be tomorrow. There'll be a v1.2.8 or whatever by then. But for now follow as above, and link your nrl.com account to your live pass in the app then use nrl.com in the addon settings.

**Comment by glennguy** [comment]
v1.3.0 released, please update and let me know how you go

**Comment by ceptic** [comment]
Looks like it is working again with v1.3.0 as I can now access post match videos. Will have to wait until a game later today to see if live stream works.

Thanks for your quick response and effort on this add-on!!

**Comment by Gumster5** [comment]
Hey got the update to 1.30 now getting a different error
'Play.py (32)- UnboundLocalError: local variable 'xml' referenced before assignment
Would you like to automatically report this error?"

**Comment by Gumster5** [comment]
Disregard above got it working.. had paid account selected instead of telstra

**Comment by ceptic** [comment]
Everything working nicely again with v1.3.0. on two of my units I had to 'Remove stored login token' to get the error to go away.

**Comment by glennguy** [comment]
@ceptic @Gumster5 
Thanks heaps for letting me know the errors you've been getting. It'll help me to implement some code to hopefully avoid these problems for other users.

Cheers
