### ISSUE TITLE
(UN) Hide Watched Videos

### ISSUE THREAD

**Issue by Corshan1** [aussieaddons/plugin.video.nrl-live#665]
I started watching a live match and then had to switch off. 10 mins later when I came back the live stream was no longer available to watch (even though it was still on).  Could it have been hidden as a result of it being watched. I could not find a toggle to.change this setting.

**Comment by glennguy** [comment]
Hi @Corshan1 

What skin are you using? I have Estuary and there's no setting when you tap left in the addon's menus/folders to hide watched videos, but maybe there is in another skin?

Which game was this for btw?

**Comment by Corshan1** [comment]
Hi. I also am using Estuary. The video in question was the first game of Friday if I recall correctly.

I will try some other skins in the meantime.

**Comment by glennguy** [comment]
No issues here with my Estuary - Kodi 17.6 on Windows.

Kodi will always mark the live matches as watched as you're always technically at the end of the video when you press stop.

I think though that it may have been something else causing the match not to display. Let me know how you go with this afternoons games if you're watching and have any issues.
