### ISSUE TITLE
No Sound on any of the 2018 highlights or match replays

### ISSUE THREAD

**Issue by dannijezza** [aussieaddons/plugin.video.nrl-live#667]
Hi I have checked my settings when I go to watch content from last year including grand final everything is fine however when I go to watch any replays from this year I have no sound at all just the picture. I have updated to Kodi 17.6 about a month ago. This was the first Time I had tried the app this year. On last year files I can see the H264 file with aac audio when pressing however on this year files I just see H264 and no Audio content.

**Comment by glennguy** [comment]
Hi @dannijezza 

Thanks for filing this report - I can verify this is a problem.

We will have to remove the setting to select the stream quality in the add-on and let Kodi do the deciding. This will result in a bit of extra time taken for the stream to start as Kodi will test all the available streams/resolutions available before deciding which one it can best handle. I'll sort that tonight.

Going forward though (and I might see if I can get it done at the same time) I'll add support to use inputstream.adaptive (Kodi 17+) to handle the streams in Kodi. Streams will start up very quick and you can fine tune the settings in the inputstream.adaptive add-on for your connection, and even manually switch streams while watching (automatic 'adaptive' stream switching is yet to be developed, not up to me/part of this add-on though).

**Comment by glennguy** [comment]
@dannijezza version 1.3.3 is now up, should solve this for you :)

**Comment by kanga71au** [comment]
Sorry glennguy i have the same issue. I cant find your version 1.3.3 tho?

**Comment by kanga71au** [comment]
Found it

**Comment by dannijezza** [comment]
Thankyou Glennguy the problem seems to be resolved.
