### ISSUE TITLE
Unable to watch any Videos

### ISSUE THREAD

**Issue by dino3157** [aussieaddons/plugin.video.nrl-live#670]
Hello, I have the NRL Live app as an add on, it was working fine the other week when I was using my Telstra ID, however I have since left Telstra. I signed up for an NRL Account and changed the Account from Free to Paid and input my nrl account details, however it comes up with the following error:

play.py (32) - HTTPError: 403 Client Error: Forbidden for URL:
https://signon-live.nrl.yinzcam.com/ticket?ff=mobile&carrier=Tetlst

I have submitted an issue on this through the Kodi box which was submitted with the number 2938.

Any help would be amazing.

Thank you

**Comment by glennguy** [comment]
Hi @dino3157 
I've had a look and can reproduce the error manually - the problem for me is that I've got no idea what is causing it on your end.

If you're willing, I'd have a pretty good chance at fixing it if I could get a hold of your credentials. If you're OK with that then you should contact me in our slack channel - http://slack-invite.aussieaddons.com/ and I should be able to get on top of it pretty quickly.
