### ISSUE TITLE
NRL Live v1.4.2 Error

### ISSUE THREAD

**Issue by shavanni** [aussieaddons/plugin.video.nrl-live#671]
Trying to watch the charity shield, when trying to get into the live matches menu, you get a error. Max retries exceeded with url. Too many 500 error

**Comment by glennguy** [comment]
Hi @shavanni
Could you turn on debug logging and recreate the error, then submit a user report from the add-on's settings and write back here with the issue number?

**Comment by shavanni** [comment]
Hi Glenn
I'm no longer getting the error. 
Live matches menu is now loading fine. 
It seems this was only whilst the charity shield was on last night.

**Comment by glennguy** [comment]
Ah ok. I'll have to keep an eye out for any future 'special events' that might cause this. Thanks!
