### ISSUE TITLE
New error wit NRL Live app

### ISSUE THREAD

**Issue by jms007316** [aussieaddons/plugin.video.nrl-live#676]
hi guys 
tonight trying to load my nrl live app on the KODI application - when clicking on the app i get an error top right “NRL Live Error - Check the log for more information”

not sure where the log is but i can check it if someone can point it out to me and add it’s contents 

images attached of error 
when the error goes away the menu options that remain are that of movies, files, playlists etc 

images attached 
![AC7DF3C9-A102-4375-B3F6-74D98E9F80C1](https://user-images.githubusercontent.com/48550928/64856883-6cb01c80-d666-11e9-844d-89e1bbf3eb1a.jpeg)
![D5A14B9F-E72A-4DFA-89EF-8F3788BDB60B](https://user-images.githubusercontent.com/48550928/64856884-6cb01c80-d666-11e9-8d2f-b2227153d7ec.jpeg)

**Comment by glennguy** [comment]
Hi @jms007316 

Thanks heaps for submitting the issue.

I've made a fix and version 1.5.1 is now available. You'll need to force refresh the repository to see it.

In the default (estuary) skin:

Go into Add-ons -> go into the 'open box' icon -> install from repository -> highlight our repo and bring up the context menu (long press, 'c', or right click) and select 'Check for updates'

Should then be good to go :) Let us know how you go!

Cheers

Glenn

**Comment by jms007316** [comment]
sensational. gotta love it. thanks for the quick response and fix too. everything worked exactly how you described it

**Comment by glennguy** [comment]
Hey no problems, thanks for letting me know there was an issue. I did a huge update today and it worked fine on my PC setup but I should have tested it on my TV - had the same issue as you did! My bad.
